/* Copyright 2005 Cenqua Pty Ltd. All Rights Reserved. See LICENSE.TXT in the distribution. */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cenqua_shaj_Shaj */

#ifndef _Included_com_cenqua_shaj_Shaj
#define _Included_com_cenqua_shaj_Shaj
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: sInitOkay */
/*
 * Class:     com_cenqua_shaj_Shaj
 * Method:    initlibrary
 * Signature: (Lcom/cenqua/shaj/Log;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cenqua_shaj_Shaj_initlibrary
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
