/* Copyright 2005 Cenqua Pty Ltd. All Rights Reserved. See LICENSE.TXT in the distribution. */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cenqua_shaj_PAMAuthenticator */

#ifndef _Included_com_cenqua_shaj_PAMAuthenticator
#define _Included_com_cenqua_shaj_PAMAuthenticator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cenqua_shaj_PAMAuthenticator
 * Method:    isSupportedImpl
 * Signature: (Lcom/cenqua/shaj/Log;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cenqua_shaj_PAMAuthenticator_isSupportedImpl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cenqua_shaj_PAMAuthenticator
 * Method:    checkPasswordImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/cenqua/shaj/Log;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cenqua_shaj_PAMAuthenticator_checkPasswordImpl
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_cenqua_shaj_PAMAuthenticator
 * Method:    checkGroupMembershipImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/cenqua/shaj/Log;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cenqua_shaj_PAMAuthenticator_checkGroupMembershipImpl
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
